const constants = {
	INDEX_CHARACTERS: 'INDEX_CHARACTERS',
	ADD_CHARACTER: 'ADD_CHARACTER',
	REMOVE_CHARACTER: 'REMOVE_CHARACTER',
	FILTER_NAME: 'FILTER_NAME',
	FILTER_TAKEN_BY: 'FILTER_TAKEN_BY',
	FILTER_KILLED_BY: 'FILTER_KILLED_BY',
	FILTER_CAUSE_OF_DEATH: 'FILTER_CAUSE_OF_DEATH',
	FILTER_BY_TERM: 'FILTER_BY_TERM',

};

export default constants;
